name: TYPEON
markdown: kramdown
highlighter: rouge
url:
paginate: 8
description:     South Korean Linux Server Programmer
intro: Special Hot Alien ?! ;-)
logo:             logo.png
disqus_shortname: typeon-github-io
# url: http://gotchacode.com
#Comment out url when working locally to resolve base urls correctly
#url:

# Owner/author information
owner:
  name:           Sangbae Kang
  avatar:         https://s.gravatar.com/avatar/3c096e8b1c0ae784a2e38bdf9c18483b?s=80
  email:          typeon@gmail.com
  # Social networking links used in footer. Update and remove as you like.
  twitter:
  github:         typeon@gmail.com
  stackexchange:
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    typeon@gmail.com

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
gems: [jekyll-paginate]
